version: '3.7'

services:
  mosquitto_server:
    image: eclipse-mosquitto
    container_name: mosquitto_server
    hostname: mosquitto_server
    restart: unless-stopped
    ports:
      - 1883:1883
      - 8888:8888
    volumes:
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/logs:/mosquitto/logs
      - ./mosquitto/conf:/mosquitto/config
